### PR TITLE
Renamed file to conform to PSR-4

### PR DESCRIPTION
**Pull request by kaptk2**
This will close issue #3 and lets the library work in modern PHP environments.

### CODE REVIEW

**Comment by flowdee** [comment]
Would be great to get this merged and released asap @ahmadawais

**Comment by JorisDebonnet** [comment]
@kaptk2, should work indeed, but can you make one addition? Just re-add a tiny file Sendy.php with the contents `require('API.php');`. This way, this PR is backwards compatible for people that include Sendy.php 😄

**Comment by JorisDebonnet** [comment]
Thanks for the addition! @ahmadawais, this is now backwards compatible, what do you think?

**Comment by JorisDebonnet** [comment]
Hi @ahmadawais, I guess this may be hard to merge now because `Sendy.php` received changes since this PR was first created. Should this PR be redone on master for it to be accepted?

**Review by ahmadawais — APPROVED** [review]
Looks good to me! ✔︎

**Comment by JorisDebonnet** [comment]
The final commit on this PR says it was merged into master, but I can't see it on master ... I'm confused 😄 Did the merge succeed?

**Comment by ahmadawais** [comment]
This was fixed in the v6.0.0. There are breaking changes. You need to now use `\AhmadAwais\Sendy\API` where `API` is the class name and the rest is the namespace.

**Pull request closed without merging**
