### PR TITLE
Add api key to all calls

### PR DESCRIPTION
**Pull request by BitpopCoin**
All functions now require api key

### CODE REVIEW

**Comment by BitpopCoin** [comment]
#7

**Comment by BitpopCoin** [comment]
I added it to the global.

**Comment by JorisDebonnet** [comment]
It works, nice work! 

The owner might ask you to squash the commits together into one, if you can do that, to have a cleaner history. Other than that, I'd say this can be merged and it fixes #7 indeed.

**Comment by ahmadawais** [comment]
Thanks for the PR. There were conflicts and I just fixed it in a separate commit.

**Comment by BitpopCoin** [comment]
You forgot to set these to 1


			// Comment to disable this SSL peer verification for testing.
			curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, 0 );
			// Comment to disable this SSL host verification for testing.
			curl_setopt( $ch, CURLOPT_SSL_VERIFYHOST, 0 );

**Comment by ahmadawais** [comment]
Please check the latest update, I am still working on crafting the final release.

**Comment by BitpopCoin** [comment]
Looks good now

**Pull request closed without merging**
